# Generated by Django 5.1.1 on 2026-01-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='requiere_suscripcion',
            field=models.BooleanField(default=False, help_text='Indica si esta materia requiere suscripción premium para acceder', verbose_name='Requiere Suscripción Premium'),
        ),
    ]
