services:
  - type: web
    name: meetwin-app
    env: python
    plan: free
    buildCommand: bash build.sh
    startCommand: gunicorn meetwin.wsgi --timeout 120 --workers 2
    envVars:
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.0"
