# Generated by Django 5.1.1 on 2026-01-05 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0002_alter_contenido_options_contenido_es_obligatorio_and_more'),
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.materia', verbose_name='Materia'),
        ),
    ]
