# Generated by Django 5.1.1 on 2026-01-05 21:33

import django.db.models.deletion
from django.db import migrations, models


def migrar_materias_a_fk(apps, schema_editor):
    """Migrar datos de texto a ForeignKey"""
    Contenido = apps.get_model('contenido', 'Contenido')
    Materia = apps.get_model('materias', 'Materia')
    
    # Actualizar cada contenido para asociarlo con una materia
    for contenido in Contenido.objects.all():
        if contenido.materia_texto:
            # Buscar o crear la materia
            materia, created = Materia.objects.get_or_create(
                nombre=contenido.materia_texto,
                defaults={'descripcion': f'Materia creada automáticamente'}
            )
            contenido.materia = materia
            contenido.save(update_fields=['materia'])


def revertir_migracion(apps, schema_editor):
    """Revertir la migración"""
    Contenido = apps.get_model('contenido', 'Contenido')
    
    for contenido in Contenido.objects.all():
        if contenido.materia:
            contenido.materia_texto = contenido.materia.nombre
            contenido.save(update_fields=['materia_texto'])


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0002_alter_contenido_options_contenido_es_obligatorio_and_more'),
        ('materias', '0001_initial'),
    ]

    operations = [
        # Paso 1: Crear campo temporal para guardar los textos
        migrations.AddField(
            model_name='contenido',
            name='materia_texto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Materia (texto)'),
        ),
        # Paso 2: Copiar datos usando SQL directo
        migrations.RunSQL(
            sql='UPDATE contenido_contenido SET materia_texto = materia;',
            reverse_sql='UPDATE contenido_contenido SET materia = materia_texto;'
        ),
        # Paso 3: Eliminar el campo antiguo materia
        migrations.RemoveField(
            model_name='contenido',
            name='materia',
        ),
        # Paso 4: Crear el nuevo campo materia como ForeignKey
        migrations.AddField(
            model_name='contenido',
            name='materia',
            field=models.ForeignKey(
                blank=True, 
                null=True, 
                on_delete=django.db.models.deletion.CASCADE, 
                to='materias.materia', 
                verbose_name='Materia'
            ),
        ),
        # Paso 5: Migrar los datos con Python
        migrations.RunPython(migrar_materias_a_fk, revertir_migracion),
    ]
